// 40 award-winning design systems — extracted token sets.
// Each object is enough to re-skin a mock website preview.
window.DESIGN_SYSTEMS = [
  {
    "id": "01",
    "name": "Lando Norris",
    "url": "https://landonorris.com",
    "award": "Awwwards Site of the Year 2025",
    "category": "Cinematic Sports / Dark Mode",
    "mode": "dark",
    "tagline": "High-contrast dark cinema where every scroll accelerates through a tunnel of papaya orange and white.",
    "principles": ["Video is the primary medium, not decoration", "Enormous, unapologetic typography", "Orange only for interactive highlights, never large fills", "High-contrast white-on-black backbone", "Flat and cinematic, no shadows"],
    "fonts": { "sans": "\"Aeonik Pro\", \"Helvetica Neue\", Arial, sans-serif", "display": "\"Aeonik Pro\", \"Helvetica Neue\", Arial, sans-serif", "mono": null },
    "typeScale": { "display": "120px", "h1": "120px", "h2": "72px", "body": "16px" },
    "weights": { "heading": 800, "body": 400 },
    "letterSpacingDisplay": "-0.03em",
    "colors": { "bg": "#0A0A0A", "bgAlt": "#1A1A1A", "surface": "#141414", "text": "#FFFFFF", "textMuted": "#A0A0A0", "border": "#333333", "primary": "#FF8000", "primaryHover": "#FF9933", "onPrimary": "#0A0A0A", "accent2": "#FFB366" },
    "heroGradient": "linear-gradient(180deg, transparent 0%, #0A0A0A 100%)",
    "radius": "0px", "buttonRadius": "0px", "shadow": "none",
    "signature": "Full-viewport video backgrounds with aggressive typographic overlay — headlines at 120px+ sitting directly on top of moving footage. Creates a broadcast-quality sports title sequence feel. Horizontal scroll sections use scroll-snap to push through content like accelerating through gears."
  },
  {
    "id": "02",
    "name": "Dropbox Brand",
    "url": "https://brand.dropbox.com",
    "award": "CSSDA Website of the Year 2025",
    "category": "Swiss Minimal / Brand Guidelines",
    "mode": "light",
    "tagline": "Ultra-clean Swiss minimalism — a design system about a design system, precise enough to cut glass.",
    "principles": ["Relentless restraint — the medium is the message", "One typeface for everything", "Color deployed surgically: blue for interaction, navy for text", "Whitespace does the talking (160px section spacing)", "Flat doctrine — zero decorative gradients or shadows"],
    "fonts": { "sans": "\"Sharp Grotesk\", \"Inter\", \"Helvetica Neue\", sans-serif", "display": "\"Sharp Grotesk\", \"Inter\", \"Helvetica Neue\", sans-serif", "mono": "\"IBM Plex Mono\", \"Fira Code\", monospace" },
    "typeScale": { "display": "96px", "h1": "80px", "h2": "56px", "body": "18px" },
    "weights": { "heading": 700, "body": 400 },
    "letterSpacingDisplay": "-0.02em",
    "colors": { "bg": "#FFFFFF", "bgAlt": "#F7F7F8", "surface": "#FFFFFF", "text": "#1E1919", "textMuted": "#6B6B6B", "border": "#E8E8E8", "primary": "#0061FF", "primaryHover": "#004FCC", "onPrimary": "#FFFFFF", "accent2": "#7B68EE" },
    "heroGradient": "linear-gradient(135deg, #0061FF 0%, #7B68EE 100%)",
    "radius": "12px", "buttonRadius": "8px", "shadow": "0 4px 16px rgba(0, 0, 0, 0.08)",
    "signature": "A brand guidelines site that uses its own rules so precisely that the medium is the message. Color swatches live inside the same 12-column grid that defines them, and typography samples use the exact specs they document. Borders, not shadows, define every boundary."
  },
  {
    "id": "03",
    "name": "Charles Leclerc",
    "url": "https://charlesleclerc.com",
    "award": "CSSDA #3 of 2025 (8.85)",
    "category": "Editorial Luxury / Motorsport",
    "mode": "dark",
    "tagline": "Editorial luxury meets motorsport — serif gravitas, deep blacks, and Ferrari red as deliberate punctuation.",
    "principles": ["Photography drives the palette, not the reverse", "Ferrari red only as text accents and thin rules, never fills", "Dark/light sections alternate for editorial rhythm", "Serif headings for gravitas, sans-serif body for modernity", "Every reveal feels like turning a coffee-table page"],
    "fonts": { "sans": "\"Neue Haas Grotesk\", \"Helvetica Neue\", Arial, sans-serif", "display": "\"EB Garamond\", \"Georgia\", \"Times New Roman\", serif", "mono": null },
    "typeScale": { "display": "120px", "h1": "96px", "h2": "64px", "body": "17px" },
    "weights": { "heading": 400, "body": 400 },
    "letterSpacingDisplay": "-0.01em",
    "colors": { "bg": "#0D0D0D", "bgAlt": "#F5F0EB", "surface": "#1A1A1A", "text": "#F5F0EB", "textMuted": "#888888", "border": "#333333", "primary": "#C12C2C", "primaryHover": "#E03333", "onPrimary": "#FFFFFF", "accent2": "#C5A55A" },
    "heroGradient": "linear-gradient(180deg, transparent 30%, rgba(13,13,13,0.95) 100%)",
    "radius": "0px", "buttonRadius": "0px", "shadow": "0 4px 20px rgba(0,0,0,0.06)",
    "signature": "Cinematic scroll-triggered image reveals — photographs masked behind dark overlays that slide away as you scroll, creating a film-strip reveal effect. Combined with EB Garamond serif headlines and a central timeline axis, the site reads like an autobiographical documentary."
  },
  {
    "id": "04",
    "name": "Immersive Garden",
    "url": "https://immersive-g.com",
    "award": "Awwwards Agency of the Year 2025",
    "category": "Dark Luxury / WebGL Portfolio",
    "mode": "dark",
    "tagline": "Dark opulence meets digital craftsmanship — cinematic WebGL scenes, refined serif type, whispered gold accents.",
    "principles": ["Interaction as performance art", "Color is scarce — scarcity creates value", "Gold only for interactive elements and the cursor, never backgrounds", "Warm off-white text, never pure white", "WebGL depth that flat design cannot touch"],
    "fonts": { "sans": "\"Sora\", \"Helvetica Neue\", sans-serif", "display": "\"Playfair Display\", \"Georgia\", serif", "mono": null },
    "typeScale": { "display": "100px", "h1": "88px", "h2": "64px", "body": "16px" },
    "weights": { "heading": 400, "body": 300 },
    "letterSpacingDisplay": "0em",
    "colors": { "bg": "#080808", "bgAlt": "#111111", "surface": "#1C1C1C", "text": "#F2EDE8", "textMuted": "#8A8A8A", "border": "#333333", "primary": "#C5A55A", "primaryHover": "#E8D5A0", "onPrimary": "#080808", "accent2": "#A8893D" },
    "heroGradient": "radial-gradient(ellipse at center, transparent 60%, #080808 100%)",
    "radius": "0px", "buttonRadius": "0px", "shadow": "none",
    "signature": "A custom gold cursor that breathes and transforms by context — shrinking over text, expanding with a 'View' label over images, a gentle gold dot over the background. Combined with WebGL shader transitions between pages, the whole experience feels like navigating a gallery rather than a website."
  },
  {
    "id": "05",
    "name": "Scout Motors",
    "url": "https://www.scoutmotors.com",
    "award": "Awwwards E-commerce of the Year 2025",
    "category": "Rugged Heritage / Automotive E-commerce",
    "mode": "light",
    "tagline": "Rugged heritage meets modern precision — earth tones and industrial type designed in a workshop, not a studio.",
    "principles": ["Scout Green for major brand moments, Rust as the attention-grabber", "Everything muted, natural, weathered — never bright or saturated", "Sand and cream backgrounds alternate for rhythm", "Heritage storytelling justifies the purchase", "Industrial, purposeful typography"],
    "fonts": { "sans": "\"Barlow\", \"Helvetica Neue\", sans-serif", "display": "\"Barlow Condensed\", \"Arial Narrow\", sans-serif", "mono": "\"IBM Plex Mono\", monospace" },
    "typeScale": { "display": "120px", "h1": "96px", "h2": "64px", "body": "17px" },
    "weights": { "heading": 700, "body": 400 },
    "letterSpacingDisplay": "0.02em",
    "colors": { "bg": "#F5F0E6", "bgAlt": "#EDE7D9", "surface": "#EDE7D9", "text": "#1C1C1C", "textMuted": "#9B9589", "border": "#D4C5A9", "primary": "#A0522D", "primaryHover": "#C0633A", "onPrimary": "#F5F0E6", "accent2": "#2D3E2F" },
    "heroGradient": "linear-gradient(180deg, transparent 40%, rgba(28,28,28,0.85) 100%)",
    "radius": "8px", "buttonRadius": "4px", "shadow": "0 2px 8px rgba(0,0,0,0.06)",
    "signature": "A full-screen vehicle configurator fused with heritage storytelling — the site transitions seamlessly from a 'once upon a time' brand narrative directly into a 'build yours' configurator. The emotional story justifies the purchase without ever feeling like a sales pitch."
  },
  {
    "id": "06",
    "name": "Bürocratik",
    "url": "https://www.burocratik.com",
    "award": "CSSDA Best Agency + EDAwards #1 Europe",
    "category": "Editorial Maximalism / Monochrome Brutalist",
    "mode": "light",
    "tagline": "Editorial maximalism in monochrome — oversized type, absolute black-and-white contrast, red as an exclamation mark.",
    "principles": ["The palette is binary: black or white, period", "Red appears only once per page — extreme restraint", "Oversized typography dominates every viewport", "Whitespace is weaponized", "Numbered manifesto structure anchors every section"],
    "fonts": { "sans": "\"Neue Montreal\", \"Helvetica Neue\", Arial, sans-serif", "display": "\"Neue Montreal\", \"Helvetica Neue\", Arial, sans-serif", "mono": null },
    "typeScale": { "display": "200px", "h1": "160px", "h2": "96px", "body": "18px" },
    "weights": { "heading": 900, "body": 400 },
    "letterSpacingDisplay": "-0.04em",
    "colors": { "bg": "#FFFFFF", "bgAlt": "#000000", "surface": "#1A1A1A", "text": "#000000", "textMuted": "#888888", "border": "#CCCCCC", "primary": "#FF3D3D", "primaryHover": "#FF5555", "onPrimary": "#FFFFFF", "accent2": "#FF3D3D" },
    "heroGradient": "#FFFFFF",
    "radius": "0px", "buttonRadius": "0px", "shadow": "none",
    "signature": "The numbered manifesto structure — every section opens with an oversized outlined numeral (01, 02, 03...) anchoring content like chapter markers in a bold publication. Combined with max-width typography that fills the viewport and infinite marquee strips between sections, it reads like a design agency's declaration of principles."
  },
  {
    "id": "07",
    "name": "Stripe",
    "url": "https://stripe.com",
    "award": "Multiple Webby Awards",
    "category": "Developer Fintech / Gradient Dark",
    "mode": "dark",
    "tagline": "Premium fintech built for developer trust — deep navy depth punctuated by living, breathing gradient purples.",
    "principles": ["Precision over decoration", "Developer-first clarity", "Gradient depth, not flat color", "Generous spacing with tight typographic control", "Code is first-class content"],
    "fonts": { "sans": "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif", "display": "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif", "mono": "\"JetBrains Mono\", \"Fira Code\", \"Courier New\", monospace" },
    "typeScale": { "display": "72px", "h1": "56px", "h2": "40px", "body": "16px" },
    "weights": { "heading": 700, "body": 400 },
    "letterSpacingDisplay": "-0.03em",
    "colors": { "bg": "#0A2540", "bgAlt": "#060F1E", "surface": "#0D3151", "text": "#FFFFFF", "textMuted": "rgba(255,255,255,0.75)", "border": "rgba(255,255,255,0.12)", "primary": "#635BFF", "primaryHover": "#4B45CC", "onPrimary": "#FFFFFF", "accent2": "#00A3FF" },
    "heroGradient": "radial-gradient(ellipse at 20% 50%, #635BFF33 0%, transparent 60%), radial-gradient(ellipse at 80% 20%, #00A3FF22 0%, transparent 60%), radial-gradient(ellipse at 50% 80%, #8B45FF22 0%, transparent 60%), #0A2540",
    "radius": "12px", "buttonRadius": "8px", "shadow": "0 4px 12px rgba(99,91,255,0.35)",
    "signature": "The animated mesh gradient hero — a dark navy canvas layered with multiple animated radial gradients in purple and cyan that shift on a slow 12s cycle, creating an organic sense of depth. Glass-effect cards float above it alongside pixel-perfect code blocks: this is what premium developer infrastructure looks like."
  },
  {
    "id": "08",
    "name": "Linear",
    "url": "https://linear.app",
    "award": "Awwwards Honoree",
    "category": "Ultra-Refined Dark SaaS",
    "mode": "dark",
    "tagline": "The gold standard for dark SaaS — near-black surfaces, gossamer glass cards, gradient-text accents, keyboard-native.",
    "principles": ["Maximum signal, minimum noise", "Dark-first: light mode is an afterthought", "Typography as primary visual element", "Glass morphism done with discipline, not excess", "Keyboard-native interaction patterns made visible"],
    "fonts": { "sans": "Inter, -apple-system, BlinkMacSystemFont, system-ui, sans-serif", "display": "Inter, -apple-system, BlinkMacSystemFont, system-ui, sans-serif", "mono": "\"Berkeley Mono\", \"JetBrains Mono\", \"SF Mono\", monospace" },
    "typeScale": { "display": "64px", "h1": "48px", "h2": "36px", "body": "15px" },
    "weights": { "heading": 700, "body": 400 },
    "letterSpacingDisplay": "-0.04em",
    "colors": { "bg": "#0A0A0A", "bgAlt": "#111111", "surface": "#161616", "text": "#F5F5F5", "textMuted": "rgba(245,245,245,0.65)", "border": "rgba(255,255,255,0.08)", "primary": "#7C5CFC", "primaryHover": "#5E85FA", "onPrimary": "#FFFFFF", "accent2": "#4EA8DE" },
    "heroGradient": "linear-gradient(135deg, #7C5CFC 0%, #5E85FA 50%, #4EA8DE 100%)",
    "radius": "12px", "buttonRadius": "6px", "shadow": "0 0 20px rgba(124,92,252,0.3)",
    "signature": "Gradient-filled headlines paired with pervasive keyboard-shortcut visual language. The purple-to-blue gradient applied to background-clip:text on large headings is instantly recognizable, while scattered kbd chips declare a keyboard-first philosophy. Linear was engineered for people who optimize everything."
  },
  {
    "id": "09",
    "name": "Vercel",
    "url": "https://vercel.com",
    "award": "Webby Nominee",
    "category": "Stark Monochrome",
    "mode": "dark",
    "tagline": "Absolute monochrome where raw performance numbers in giant Geist type are the only decoration.",
    "principles": ["Zero color — contrast is the only accent", "Typography as architecture", "Terminal/code aesthetics elevated to marketing", "Performance numbers as decorative elements", "Geometry (triangle) as recurring motif"],
    "fonts": { "sans": "\"Geist Sans\", \"Geist\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif", "display": "\"Geist Sans\", \"Geist\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif", "mono": "\"Geist Mono\", \"SF Mono\", \"Fira Code\", monospace" },
    "typeScale": { "display": "72px", "h1": "64px", "h2": "48px", "body": "14px" },
    "weights": { "heading": 900, "body": 400 },
    "letterSpacingDisplay": "-0.04em",
    "colors": { "bg": "#000000", "bgAlt": "#0A0A0A", "surface": "#111111", "text": "#FFFFFF", "textMuted": "#888888", "border": "#333333", "primary": "#FFFFFF", "primaryHover": "#CCCCCC", "onPrimary": "#000000", "accent2": "#0070F3" },
    "heroGradient": "#000000",
    "radius": "0px", "buttonRadius": "0px", "shadow": "none",
    "signature": "Vercel's fingerprint is using raw performance data as the primary visual element — '0.7s' in 72px Geist Black, white on black, is the hero where others use imagery. The zero-color constraint is so absolute it becomes a brand statement, and the triangle (▲) is the only shape. Performance is the aesthetic."
  },
  {
    "id": "10",
    "name": "Apple",
    "url": "https://apple.com",
    "award": "Multiple Webby Awards",
    "category": "Consumer Premium Editorial",
    "mode": "light",
    "tagline": "High-end print advertising that happens to be interactive — restraint, photography, and SF Pro at scale.",
    "principles": ["Singular focus — one product, one story per page", "Photography as hero at cinematic scale", "Motion as revelation via scroll-driven animation", "Typography-first hierarchy — size and weight carry meaning", "Frictionless commerce — always-visible, never aggressive"],
    "fonts": { "sans": "\"SF Pro Text\", system-ui, -apple-system, BlinkMacSystemFont, \"Helvetica Neue\", sans-serif", "display": "\"SF Pro Display\", system-ui, -apple-system, BlinkMacSystemFont, \"Helvetica Neue\", sans-serif", "mono": null },
    "typeScale": { "display": "96px", "h1": "56px", "h2": "40px", "body": "17px" },
    "weights": { "heading": 700, "body": 400 },
    "letterSpacingDisplay": "-0.025em",
    "colors": { "bg": "#F5F5F7", "bgAlt": "#FFFFFF", "surface": "#FFFFFF", "text": "#1D1D1F", "textMuted": "#6E6E73", "border": "#D2D2D7", "primary": "#0071E3", "primaryHover": "#0077ED", "onPrimary": "#FFFFFF", "accent2": "#0071E3" },
    "heroGradient": "linear-gradient(180deg, #FFFFFF 0%, #F5F5F7 100%)",
    "radius": "18px", "buttonRadius": "980px", "shadow": "0 2px 8px rgba(0,0,0,0.08)",
    "signature": "Apple is recognizable by its 980px centered island floating in vast gray space like a framed exhibit, and by pinned-scroll reveals where products assemble as you scroll. Pages alternate between gray, white and black sections in a deliberate rhythm, with SF Pro's negative tracking at 96px and a frosted blur nav."
  },
  {
    "id": "11",
    "name": "Audo Copenhagen",
    "url": "https://audo.com",
    "award": "Webby Award Winner 2025 (Best Design)",
    "category": "Scandinavian Luxury / Interior E-Commerce",
    "mode": "light",
    "tagline": "A coffee-table book about Scandinavian design — warm whites, brass, and editorial serifs at light weight.",
    "principles": ["Hygge as UI — warmth from texture, not busyness", "Architectural photography as navigation", "Restraint as luxury — no borders, shadows, or gradients", "Craft over convention — editorial, never transactional typography", "Slow scroll — designed to inhabit, not rush"],
    "fonts": { "sans": "\"Suisse Intl\", -apple-system, BlinkMacSystemFont, \"Helvetica Neue\", Arial, sans-serif", "display": "\"Freight Display Pro\", Georgia, \"Times New Roman\", serif", "mono": "\"Courier New\", monospace" },
    "typeScale": { "display": "88px", "h1": "56px", "h2": "40px", "body": "16px" },
    "weights": { "heading": 400, "body": 300 },
    "letterSpacingDisplay": "-0.02em",
    "colors": { "bg": "#F5F0EB", "bgAlt": "#EDE8E1", "surface": "#EDE8E1", "text": "#2C2C2C", "textMuted": "#8B8172", "border": "#D8D0C6", "primary": "#2C2C2C", "primaryHover": "#C4A882", "onPrimary": "#F5F0EB", "accent2": "#C4A882" },
    "heroGradient": "linear-gradient(180deg, #FAF8F5 0%, #F5F0EB 100%)",
    "radius": "0px", "buttonRadius": "0px", "shadow": "none",
    "signature": "Audo's identity rests on the warm white #F5F0EB foundation — never cold — and Freight Display used at weight 300–400, never bold. Square buttons signal Bauhaus over tech, while product cards carry no borders or shadows because the products sell themselves. Brass #C4A882 is the sole accent."
  },
  {
    "id": "12",
    "name": "KLABU",
    "url": "https://klabu.org",
    "award": "Webby People's Voice 2025",
    "category": "Social Impact / Athletic",
    "mode": "dark",
    "tagline": "Stadium-scale athletic typography and electric signal colors turn humanitarian data into a call to action.",
    "principles": ["Urgency over elegance — high contrast and signal colors", "Sport as visual language — condensed athletic type, kinetic energy", "Data as storytelling — impact numbers animate and grow", "Split thinking — split-screen layouts mirror two worlds", "No apology aesthetics — nothing soft, rounded, or neutral"],
    "fonts": { "sans": "\"Barlow\", -apple-system, BlinkMacSystemFont, \"Helvetica Neue\", Arial, sans-serif", "display": "\"Barlow Condensed\", \"Arial Narrow\", Impact, sans-serif", "mono": null },
    "typeScale": { "display": "120px", "h1": "64px", "h2": "40px", "body": "18px" },
    "weights": { "heading": 700, "body": 400 },
    "letterSpacingDisplay": "-0.01em",
    "colors": { "bg": "#1A1A1A", "bgAlt": "#2A2A2A", "surface": "#1A1A1A", "text": "#FFFFFF", "textMuted": "#888888", "border": "#444444", "primary": "#0066FF", "primaryHover": "#0052CC", "onPrimary": "#FFFFFF", "accent2": "#FF3333" },
    "heroGradient": "linear-gradient(135deg, #1A1A1A 0%, #0066FF 100%)",
    "radius": "0px", "buttonRadius": "4px", "shadow": "0 8px 24px rgba(0,102,255,0.3)",
    "signature": "KLABU deploys Barlow Condensed at 80–120px — the voice of stadium scoreboards — for humanitarian numbers, an intentional cognitive dissonance. The 50/50 split-screen layout creates two parallel realities, with thick bordered cards like scoreboard panels and animated counters in electric blue and signal red."
  },
  {
    "id": "13",
    "name": "Lacoste",
    "url": "https://www.lacoste.com",
    "award": "CSSDA #8 of 2025 (8.75)",
    "category": "Fashion / Playful Luxury",
    "mode": "light",
    "tagline": "Heritage tennis-club luxury made contemporary — sacred green, gold accents, and Playfair editorial flair.",
    "principles": ["Heritage with momentum — vintage tennis club updated for digital luxury", "The green is sacred — #004D2C is the organizing logic of every screen", "Editorial photography as premium signal", "Membership as identity — the Club tier system is a primary UI pattern", "Refined restraint — generous whitespace, slow reveals, precise gold accents"],
    "fonts": { "sans": "\"Helvetica Now Display\", \"Helvetica Neue\", Helvetica, Arial, sans-serif", "display": "\"Playfair Display\", Georgia, \"Times New Roman\", serif", "mono": null },
    "typeScale": { "display": "96px", "h1": "64px", "h2": "48px", "body": "16px" },
    "weights": { "heading": 700, "body": 300 },
    "letterSpacingDisplay": "-0.02em",
    "colors": { "bg": "#F5F1EA", "bgAlt": "#FFFFFF", "surface": "#FFFFFF", "text": "#1D1D1D", "textMuted": "#7A7A7A", "border": "#D4CABC", "primary": "#004D2C", "primaryHover": "#003620", "onPrimary": "#FFFFFF", "accent2": "#C5A661" },
    "heroGradient": "linear-gradient(to bottom, rgba(0,0,0,0.1) 0%, rgba(0,0,0,0.4) 100%), #004D2C",
    "radius": "12px", "buttonRadius": "24px", "shadow": "0 2px 12px rgba(0,0,0,0.06)",
    "signature": "Lacoste pairs Playfair Display italic at 64–96px for campaign headlines with #004D2C used as architectural material across full-bleed sections, nav, and footers. The 24px button radius is a deliberate middle ground between square and pill, and gold #C5A661 is applied with jeweler's precision over a warm cream background."
  },
  {
    "id": "14",
    "name": "ComPsych",
    "url": "https://www.compsych.com",
    "award": "CSSDA #9 of 2025 (8.74)",
    "category": "Corporate Wellness / Warm",
    "mode": "light",
    "tagline": "Rounded warmth and flat-vector people de-medicalize corporate wellness with AAA-grade accessibility.",
    "principles": ["Rounded everything — no sharp corners, nothing institutional", "Illustration-forward — warm, diverse flat vector people over photography", "Documentation-first layout with persistent sidebar", "Color-coded content using a warm teal/coral/cream palette", "Feels like a trusted colleague's office, not a hospital waiting room"],
    "fonts": { "sans": "\"DM Sans\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", system-ui, sans-serif", "display": "\"DM Sans\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", system-ui, sans-serif", "mono": "\"DM Mono\", \"Courier New\", monospace" },
    "typeScale": { "display": "48px", "h1": "32px", "h2": "28px", "body": "16px" },
    "weights": { "heading": 700, "body": 400 },
    "letterSpacingDisplay": "-0.02em",
    "colors": { "bg": "#FFF8F0", "bgAlt": "#E0F4F4", "surface": "#FFFFFF", "text": "#1A2744", "textMuted": "#6B7A9E", "border": "#D8D0C8", "primary": "#0A8A8A", "primaryHover": "#06615F", "onPrimary": "#FFFFFF", "accent2": "#E86C5A" },
    "heroGradient": "linear-gradient(135deg, #E0F4F4 0%, #FFF8F0 60%, #FAE8E5 100%)",
    "radius": "24px", "buttonRadius": "16px", "shadow": "0 2px 12px rgba(26, 39, 68, 0.08)",
    "signature": "ComPsych's signature is maximum roundness — 24px card radius, 16px button radius — paired with illustration-native characters to psychologically de-medicalize wellness. Tinted rounded illustration pods frame flat vector people, and layered depth comes from background color relationships rather than dramatic shadows."
  },
  {
    "id": "15",
    "name": "The Monolith Project",
    "url": "https://monolith.world",
    "award": "CSSDA #4 of 2025 (8.85)",
    "category": "Experimental / Anti-Design",
    "mode": "dark",
    "tagline": "Confrontational machine-aesthetic anti-design: pure black/white, all-monospace, and a cursor that is the artwork.",
    "principles": ["Binary existence — #000000 and #FFFFFF only, no greys or gradients", "Monospace supremacy — a single monospace face for everything", "Sequential revelation — numbered sections, not categories", "Cursor as actor — mouse position drives layout via parallax", "No affordances — buttons, links, and nav don't look like themselves"],
    "fonts": { "sans": "\"Space Mono\", \"JetBrains Mono\", \"Courier New\", monospace", "display": "\"Space Mono\", \"JetBrains Mono\", \"Courier New\", monospace", "mono": "\"Space Mono\", \"JetBrains Mono\", \"Courier New\", monospace" },
    "typeScale": { "display": "64px", "h1": "48px", "h2": "32px", "body": "16px" },
    "weights": { "heading": 700, "body": 400 },
    "letterSpacingDisplay": "-0.04em",
    "colors": { "bg": "#000000", "bgAlt": "#FFFFFF", "surface": "#000000", "text": "#FFFFFF", "textMuted": "rgba(255,255,255,0.4)", "border": "#FFFFFF", "primary": "#FFFFFF", "primaryHover": "#CCCCCC", "onPrimary": "#000000", "accent2": "#FFFFFF" },
    "heroGradient": "#000000",
    "radius": "0px", "buttonRadius": "0px", "shadow": "none",
    "signature": "Every decision flows from one commitment: the cursor is part of the artwork, tracked in real time to transform page elements. Zero-lag depth layers build a pseudo-3D space, anchored by huge ghost-opacity section numbers. Mechanical snap-inversions on hover and a crosshair cursor signal this is not a normal website."
  },
  {
    "id": "16",
    "name": "Symphony of Vines",
    "url": "https://thesymphonyofvines.com",
    "award": "CSSDA #2 of 2025 (8.88)",
    "category": "Wine / Cinematic Scroll",
    "mode": "dark",
    "tagline": "Cinematic wine storytelling — a slowly-unfolding film of burgundy, gold, and full-bleed vineyard photography.",
    "principles": ["Cinematic first — feels like a slowly-unfolding film", "Photography is the hero — full-bleed vineyard images carry emotion", "Typography does the talking — display serifs for all headings", "Time is architecture — the year timeline is the narrative backbone", "Motion is ambient — everything eases at 1.5 seconds minimum"],
    "fonts": { "sans": "\"Libre Baskerville\", Georgia, \"Times New Roman\", serif", "display": "\"Playfair Display\", \"Cormorant Garamond\", Georgia, serif", "mono": null },
    "typeScale": { "display": "112px", "h1": "40px", "h2": "32px", "body": "17px" },
    "weights": { "heading": 700, "body": 400 },
    "letterSpacingDisplay": "-0.02em",
    "colors": { "bg": "#1A1006", "bgAlt": "#F5F0E8", "surface": "#2B2B2B", "text": "#F5F0E8", "textMuted": "rgba(245, 240, 232, 0.6)", "border": "rgba(197, 165, 90, 0.3)", "primary": "#722F37", "primaryHover": "#4A1B22", "onPrimary": "#F5F0E8", "accent2": "#C5A55A" },
    "heroGradient": "linear-gradient(to bottom, rgba(26, 16, 6, 0) 0%, rgba(26, 16, 6, 0.7) 60%, rgba(26, 16, 6, 0.95) 100%)",
    "radius": "0px", "buttonRadius": "0px", "shadow": "none",
    "signature": "A horizontal scroll narrative where each panel is a vintage year with the year floating in large translucent numerals behind the content, advancing like a film reel. A three-layer parallax stack builds genuine 3D depth, threaded by a full-width gold timeline — making time a physical journey rather than a document."
  },
  {
    "id": "17",
    "name": "Raycast",
    "url": "https://raycast.com",
    "award": "Awwwards Site of the Day 2024",
    "category": "Developer Tool / Sleek Dark",
    "mode": "dark",
    "tagline": "A precision dark command-palette aesthetic where glass panels and purple glow simulate real interface depth.",
    "principles": ["Dark-first, not dark-mode — near-black is the canvas", "Depth through intentional layering, not decoration", "Command palette as the core interface metaphor", "Keyboard-native, developer-first signaling", "Radical restraint in saturation — one touch of color at a time"],
    "fonts": { "sans": "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif", "display": "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif", "mono": "'JetBrains Mono', 'Fira Code', monospace" },
    "typeScale": { "display": "72px", "h1": "56px", "h2": "40px", "body": "16px" },
    "weights": { "heading": 600, "body": 400 },
    "letterSpacingDisplay": "-0.04em",
    "colors": { "bg": "#0A0A0A", "bgAlt": "#111111", "surface": "rgba(255,255,255,0.05)", "text": "#FFFFFF", "textMuted": "#ABABAB", "border": "#222222", "primary": "#7C3AED", "primaryHover": "#8B5CF6", "onPrimary": "#FFFFFF", "accent2": "#3B82F6" },
    "heroGradient": "radial-gradient(ellipse 70% 50% at 50% 50%, rgba(124,58,237,0.2) 0%, rgba(59,130,246,0.1) 50%, transparent 100%)",
    "radius": "16px", "buttonRadius": "10px", "shadow": "0 32px 80px rgba(0,0,0,0.6), 0 0 0 1px rgba(255,255,255,0.04)",
    "signature": "The command palette is the aesthetic language — glass panels with purple glow trace back to the product's command bar. Keyboard shortcut badges in monospace appear everywhere, and perspective-shifted UI screenshots float in 3D space. Color pops precisely because everything else stays neutral."
  },
  {
    "id": "18",
    "name": "Notion",
    "url": "https://notion.so",
    "award": "Multiple design awards",
    "category": "Productivity / Warm Minimal",
    "mode": "light",
    "tagline": "Earned minimalism on a warm cream canvas — a well-loved notebook, not a command center.",
    "principles": ["Earned minimalism — every element serves the reader", "Content is king — reading-first at human attention scale", "Human-scaled warmth over cold enterprise sterility", "Editorial restraint with generous breathing room", "Toggle as metaphor — discovery is a gesture away"],
    "fonts": { "sans": "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, sans-serif", "display": "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, sans-serif", "mono": "'SFMono-Regular', Menlo, Monaco, Consolas, monospace" },
    "typeScale": { "display": "52px", "h1": "40px", "h2": "32px", "body": "15px" },
    "weights": { "heading": 700, "body": 400 },
    "letterSpacingDisplay": "-0.02em",
    "colors": { "bg": "#FFFEFC", "bgAlt": "#F7F6F3", "surface": "#FFFFFF", "text": "#37352F", "textMuted": "#6B6B6B", "border": "#E0E0E0", "primary": "#E16259", "primaryHover": "#C94B42", "onPrimary": "#FFFFFF", "accent2": "#4B82C4" },
    "heroGradient": "linear-gradient(180deg, #FFFEFC 0%, #F7F6F3 100%)",
    "radius": "8px", "buttonRadius": "4px", "shadow": "0 4px 16px rgba(55,53,47,0.10)",
    "signature": "Built on editorial humanism — the warm cream canvas says 'paper' before a word is read. Emoji function as first-class UI shorthand and hand-drawn illustrations humanize what could feel like a feature grid. The 900px reading width keeps layouts focused, trusting content over convention."
  },
  {
    "id": "19",
    "name": "Figma",
    "url": "https://figma.com",
    "award": "Webby Award Honoree",
    "category": "Design Tool / Colorful Play",
    "mode": "light",
    "tagline": "Design used to sell design — a bold three-color gradient manifesto rendered in chunky geometric type.",
    "principles": ["Use design to sell design", "Bold, expressive, and confidently colorful", "One gradient does the work of an entire palette", "Live embedded prototypes prove value over description", "Black CTAs on white — bold without being loud"],
    "fonts": { "sans": "'Whyte', 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif", "display": "'Whyte', 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif", "mono": "'JetBrains Mono', 'Courier New', monospace" },
    "typeScale": { "display": "80px", "h1": "48px", "h2": "36px", "body": "17px" },
    "weights": { "heading": 700, "body": 400 },
    "letterSpacingDisplay": "-0.04em",
    "colors": { "bg": "#FFFFFF", "bgAlt": "#F5F5F5", "surface": "#FFFFFF", "text": "#1E1E1E", "textMuted": "#5C5C5C", "border": "#E8E8E8", "primary": "#1E1E1E", "primaryHover": "#333333", "onPrimary": "#FFFFFF", "accent2": "#A259FF" },
    "heroGradient": "linear-gradient(135deg, #A259FF 0%, #FF7262 50%, #F24E1E 100%)",
    "radius": "16px", "buttonRadius": "8px", "shadow": "0 8px 32px rgba(0,0,0,0.12)",
    "signature": "The three-color gradient (#A259FF → #FF7262 → #F24E1E) acts as stroke, fill, text, background, and button — one gradient doing the work of an entire brand palette. The round, quirky Whyte typeface carries personality at bold weights, while black CTAs on white deliver contrast that's bold without being loud."
  },
  {
    "id": "20",
    "name": "Arc Browser",
    "url": "https://arc.net",
    "award": "Multiple design awards",
    "category": "Browser / Gradient Whimsy",
    "mode": "light",
    "tagline": "A browser that loves you back — soft gradient pills, floating screenshots, and warm Mac-native whimsy.",
    "principles": ["Whimsical warmth controlled enough to feel sophisticated", "Nothing has a sharp corner — pill shapes everywhere", "Illustration is load-bearing, not decorative", "Gradient restraint tells a product story", "SF Pro as a Mac-native trust signal"],
    "fonts": { "sans": "-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Helvetica Neue', Helvetica, Arial, sans-serif", "display": "-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Helvetica Neue', Helvetica, Arial, sans-serif", "mono": "'SF Mono', Menlo, Monaco, monospace" },
    "typeScale": { "display": "72px", "h1": "44px", "h2": "34px", "body": "17px" },
    "weights": { "heading": 700, "body": 400 },
    "letterSpacingDisplay": "-0.03em",
    "colors": { "bg": "#FAFAFA", "bgAlt": "#F0F0F0", "surface": "#FFFFFF", "text": "#1A1A1A", "textMuted": "#6B7280", "border": "#E5E7EB", "primary": "#C4B5FD", "primaryHover": "#FB923C", "onPrimary": "#1A1A1A", "accent2": "#5EEAD4" },
    "heroGradient": "linear-gradient(135deg, #C4B5FD 0%, #F9A8D4 25%, #FB923C 55%, #5EEAD4 100%)",
    "radius": "20px", "buttonRadius": "999px", "shadow": "0 32px 80px rgba(0,0,0,0.15), 0 8px 24px rgba(0,0,0,0.08)",
    "signature": "The 999px gradient pill is Arc's signature — every button, badge, and form element is soft and approachable. Floating screenshots breathe via a float animation whose shadow grows as the screen rises. The lavender → coral → teal gradient maps the emotional spectrum of browsing."
  },
  {
    "id": "21",
    "name": "Pitch",
    "url": "https://pitch.com",
    "award": "Awwwards Site of the Day",
    "category": "Presentation / Bold Color",
    "mode": "dark",
    "tagline": "Every section looks like one of Pitch's own beautiful slide templates — polished dark-violet SaaS.",
    "principles": ["The product itself is the hero — marketing as implicit demo", "Dense but breathable", "Presentation-editor metaphor bleeds into the site", "Dark-violet aesthetic communicates deck quality", "Elevated, slide-deck-precise composition"],
    "fonts": { "sans": "\"Söhne\", \"Inter\", system-ui, sans-serif", "display": "\"Söhne\", \"Inter\", system-ui, sans-serif", "mono": "ui-monospace, SFMono-Regular, Menlo, monospace" },
    "typeScale": { "display": "88px", "h1": "72px", "h2": "56px", "body": "16px" },
    "weights": { "heading": 700, "body": 400 },
    "letterSpacingDisplay": "-0.02em",
    "colors": { "bg": "#0F0E17", "bgAlt": "#161426", "surface": "#161426", "text": "#FFFFFF", "textMuted": "rgba(255,255,255,0.6)", "border": "#2D2B4E", "primary": "#7B5CF0", "primaryHover": "#8B6CF5", "onPrimary": "#FFFFFF", "accent2": "#9B7FF5" },
    "heroGradient": "linear-gradient(135deg, #0F0E17 0%, #1A1540 50%, #0F0E17 100%)",
    "radius": "16px", "buttonRadius": "8px", "shadow": "0 24px 64px rgba(0,0,0,0.6)",
    "signature": "The product itself is the hero — every section looks like one of Pitch's own beautiful slide templates. The dark-violet aesthetic communicates exactly what your deck will feel like, making the site an implicit product demonstration. Glow blobs, shimmer-bordered cards, and 3D-tilted screenshots reinforce the editor metaphor."
  },
  {
    "id": "22",
    "name": "Framer",
    "url": "https://www.framer.com",
    "award": "Awwwards Honoree",
    "category": "Design Tool / Gradient Dark",
    "mode": "light",
    "tagline": "Clean white canvas with surgical typography and electric blue — a living product demo built in Framer.",
    "principles": ["Clean white canvas with surgical typography", "The site is built in Framer — a living product demo", "Interactive previews that feel alive over screenshots", "Bento-grid clarity and precision", "Minimal, crisp motion — content appears cleanly"],
    "fonts": { "sans": "\"Inter\", system-ui, -apple-system, sans-serif", "display": "\"Inter\", system-ui, -apple-system, sans-serif", "mono": "ui-monospace, SFMono-Regular, Menlo, monospace" },
    "typeScale": { "display": "96px", "h1": "72px", "h2": "56px", "body": "16px" },
    "weights": { "heading": 700, "body": 400 },
    "letterSpacingDisplay": "-0.025em",
    "colors": { "bg": "#FFFFFF", "bgAlt": "#F5F5F7", "surface": "#FFFFFF", "text": "#0A0A0A", "textMuted": "#444444", "border": "#E5E5E5", "primary": "#0099FF", "primaryHover": "#0088EE", "onPrimary": "#FFFFFF", "accent2": "#00C6FF" },
    "heroGradient": "linear-gradient(180deg, #FFFFFF 0%, #F5F5F7 100%)",
    "radius": "16px", "buttonRadius": "8px", "shadow": "0 8px 32px rgba(0,0,0,0.08)",
    "signature": "The marketing site is built in Framer and runs live interactive product demos directly inside the page — scroll-driven canvas components, real editors. The product sells itself through direct experience. Surgical Inter typography, bento-grid layouts, and electric blue accents keep the white canvas crisp."
  },
  {
    "id": "23",
    "name": "Supabase",
    "url": "https://supabase.com",
    "award": "Dev community favorite",
    "category": "Developer / Dark Emerald",
    "mode": "dark",
    "tagline": "The terminal got a tasteful rebrand — confident dark mode anchored by unmistakable electric green.",
    "principles": ["Confident dark mode as default", "Code blocks and terminal aesthetics as core content", "Signature electric green used with total consistency", "Data flow and connection diagrams tell the platform story", "Technically legible, developer-native restraint"],
    "fonts": { "sans": "\"Inter\", system-ui, -apple-system, sans-serif", "display": "\"Inter\", system-ui, -apple-system, sans-serif", "mono": "\"JetBrains Mono\", \"Fira Code\", Menlo, monospace" },
    "typeScale": { "display": "80px", "h1": "64px", "h2": "48px", "body": "16px" },
    "weights": { "heading": 700, "body": 400 },
    "letterSpacingDisplay": "-0.02em",
    "colors": { "bg": "#1C1C1C", "bgAlt": "#161616", "surface": "#262626", "text": "#EEEEEE", "textMuted": "#AAAAAA", "border": "#3E3E3E", "primary": "#3ECF8E", "primaryHover": "#47DBA0", "onPrimary": "#1C1C1C", "accent2": "#22C55E" },
    "heroGradient": "radial-gradient(ellipse at 50% -20%, rgba(62,207,142,0.12) 0%, transparent 60%)",
    "radius": "8px", "buttonRadius": "6px", "shadow": "0 8px 32px rgba(0,0,0,0.6)",
    "signature": "That electric green #3ECF8E — singular, unmistakable, and technically legible on dark — is used so consistently it has become a developer-culture icon. The moment you see that green, you know it's Supabase. Dense code blocks, terminal aesthetics, and animated connection graphs reinforce the identity."
  },
  {
    "id": "24",
    "name": "Railway",
    "url": "https://railway.com",
    "award": "Awwwards Honoree",
    "category": "Developer Platform / Purple Neon",
    "mode": "dark",
    "tagline": "Mission control with a boutique makeover — deep near-black, glowing infra graphs, magenta-violet canvas.",
    "principles": ["Theatrical dark tech with deep near-black backgrounds", "Infrastructure as art — the visual canvas is the hero", "Glowing service graphs reframe deployment complexity", "Live counters and animated pipelines signal real-time", "Service-color coding as a visual language"],
    "fonts": { "sans": "\"Geist\", \"Inter\", system-ui, sans-serif", "display": "\"Geist\", \"Inter\", system-ui, sans-serif", "mono": "\"Geist Mono\", \"JetBrains Mono\", monospace" },
    "typeScale": { "display": "80px", "h1": "64px", "h2": "44px", "body": "16px" },
    "weights": { "heading": 700, "body": 400 },
    "letterSpacingDisplay": "-0.02em",
    "colors": { "bg": "#0B0D0F", "bgAlt": "#0D1117", "surface": "#161B22", "text": "#E6EDF3", "textMuted": "#7D8590", "border": "#30363D", "primary": "#7C3AED", "primaryHover": "#6D28D9", "onPrimary": "#FFFFFF", "accent2": "#C026D3" },
    "heroGradient": "radial-gradient(ellipse at 40% -10%, rgba(124,58,237,0.2) 0%, rgba(192,38,211,0.1) 30%, transparent 60%)",
    "radius": "12px", "buttonRadius": "6px", "shadow": "0 8px 24px rgba(0,0,0,0.6)",
    "signature": "The visual canvas — a live, interactive node graph showing your entire stack — is embedded right into the marketing page, turning infrastructure into art. Service nodes pulse and dashed connectors animate data flow, while deployment pipelines progress from violet to terminal green."
  },
  {
    "id": "25",
    "name": "Resend",
    "url": "https://resend.com",
    "award": "Awwwards Site of the Day",
    "category": "Developer Email / Minimal Dark",
    "mode": "dark",
    "tagline": "Pure black, surgical orange — a marketing site engineered like the product itself.",
    "principles": ["Zero decoration — every element earns its place", "Code blocks are the hero visuals", "Orange used as a signal, not decoration", "Typography does the heavy lifting", "Docs-adjacent, developer-first structure"],
    "fonts": { "sans": "\"Inter\", system-ui, -apple-system, sans-serif", "display": "\"Inter\", system-ui, -apple-system, sans-serif", "mono": "\"Geist Mono\", \"JetBrains Mono\", \"Fira Code\", monospace" },
    "typeScale": { "display": "64px", "h1": "64px", "h2": "36px", "body": "16px" },
    "weights": { "heading": 700, "body": 400 },
    "letterSpacingDisplay": "-0.02em",
    "colors": { "bg": "#000000", "bgAlt": "#0A0A0A", "surface": "#0A0A0A", "text": "#FFFFFF", "textMuted": "rgba(255,255,255,0.6)", "border": "#1A1A1A", "primary": "#FF4D00", "primaryHover": "#FF6A2A", "onPrimary": "#FFFFFF", "accent2": "#FF8C42" },
    "heroGradient": "radial-gradient(ellipse at 50% -20%, rgba(255, 77, 0, 0.15) 0%, transparent 60%)",
    "radius": "10px", "buttonRadius": "6px", "shadow": "0 0 20px rgba(255, 77, 0, 0.35)",
    "signature": "Resend designs its marketing site exactly like its product — pure developer utility with zero visual noise on true black. The orange accent is so reserved that when it appears it reads as a signal, not decoration. Code blocks are the hero and typography carries everything."
  },
  {
    "id": "26",
    "name": "Cal.com",
    "url": "https://cal.com",
    "award": "Webby Nominee",
    "category": "Scheduling / Open Source Clean",
    "mode": "light",
    "tagline": "Crisp off-white, deep navy type — the booking widget IS the hero.",
    "principles": ["Calendar UI previews are the core visual language", "Entirely flat design — no gradients", "Compact, precise, and trustworthy", "The product demonstrates itself", "Generous, structured white space"],
    "fonts": { "sans": "\"Inter\", system-ui, -apple-system, sans-serif", "display": "\"Cal Sans\", \"Inter\", system-ui, sans-serif", "mono": "\"Geist Mono\", \"JetBrains Mono\", monospace" },
    "typeScale": { "display": "72px", "h1": "56px", "h2": "44px", "body": "16px" },
    "weights": { "heading": 700, "body": 400 },
    "letterSpacingDisplay": "-0.02em",
    "colors": { "bg": "#FFFFFF", "bgAlt": "#F9FAFB", "surface": "#FFFFFF", "text": "#111827", "textMuted": "#6B7280", "border": "#E5E7EB", "primary": "#111827", "primaryHover": "#1F2937", "onPrimary": "#FFFFFF", "accent2": "#0069FF" },
    "heroGradient": "linear-gradient(180deg, #FFFFFF 0%, #F9FAFB 100%)",
    "radius": "12px", "buttonRadius": "6px", "shadow": "0 8px 32px rgba(0, 0, 0, 0.06)",
    "signature": "The actual booking widget is embedded directly in the marketing hero — not a screenshot or mockup, a real functional calendar component you can interact with. The product IS the hero element, rendered in crisp off-white with deep navy type and green availability slots."
  },
  {
    "id": "27",
    "name": "Mintlify",
    "url": "https://mintlify.com",
    "award": "Dev community standard",
    "category": "Documentation / Fresh Green",
    "mode": "dark",
    "tagline": "Premium dark with mint-green intelligence — documentation made aspirational.",
    "principles": ["Docs-native, hierarchical, scannable structure", "Bento grid for diverse feature callouts", "Hero always shows the real product in use", "Mint green as a focused signal", "Typography-first with excellent hierarchy"],
    "fonts": { "sans": "\"Inter\", system-ui, -apple-system, sans-serif", "display": "\"Plus Jakarta Sans\", \"Inter\", system-ui, sans-serif", "mono": "\"Geist Mono\", \"JetBrains Mono\", monospace" },
    "typeScale": { "display": "72px", "h1": "48px", "h2": "40px", "body": "17px" },
    "weights": { "heading": 700, "body": 400 },
    "letterSpacingDisplay": "-0.03em",
    "colors": { "bg": "#0D0D0D", "bgAlt": "#111111", "surface": "#111111", "text": "#FFFFFF", "textMuted": "rgba(255,255,255,0.45)", "border": "#1F1F1F", "primary": "#00C4A0", "primaryHover": "#00E5B8", "onPrimary": "#0D0D0D", "accent2": "#009E80" },
    "heroGradient": "radial-gradient(ellipse at 60% -10%, rgba(0, 196, 160, 0.18) 0%, transparent 55%)",
    "radius": "16px", "buttonRadius": "8px", "shadow": "0 0 24px rgba(0, 196, 160, 0.4)",
    "signature": "Mintlify makes documentation look aspirational — a premium dark aesthetic that says this isn't your enterprise docs tool, while mint green communicates freshness and intelligence. Bento feature cards glow mint on hover, and the hero shows real customer docs rendered in the platform."
  },
  {
    "id": "28",
    "name": "Locomotive",
    "url": "https://locomotive.ca",
    "award": "FWA Agency of the Year",
    "category": "Agency / Brutalist Motion",
    "mode": "dark",
    "tagline": "Typography at architectural scale on pure black — the site is a live case study.",
    "principles": ["Type grid itself is the layout, not text inside a layout", "Negative space pushed to the point of discomfort", "Tactile, physics-based scroll and hover states", "Restrained color — black, white, rare red", "Razor-sharp corners, flat presentation"],
    "fonts": { "sans": "\"Neue Haas Grotesk\", \"Helvetica Neue\", Arial, system-ui, sans-serif", "display": "\"Monument Extended\", \"Helvetica Neue\", \"Arial Black\", sans-serif", "mono": null },
    "typeScale": { "display": "160px", "h1": "112px", "h2": "72px", "body": "16px" },
    "weights": { "heading": 900, "body": 300 },
    "letterSpacingDisplay": "-0.02em",
    "colors": { "bg": "#000000", "bgAlt": "#0C0C0C", "surface": "#0C0C0C", "text": "#FFFFFF", "textMuted": "#888888", "border": "#1A1A1A", "primary": "#FF2800", "primaryHover": "#FF4D26", "onPrimary": "#FFFFFF", "accent2": "#F5C400" },
    "heroGradient": "linear-gradient(135deg, rgba(255,255,255,0.04) 0%, transparent 100%)",
    "radius": "0px", "buttonRadius": "0px", "shadow": "0 24px 64px rgba(0, 0, 0, 0.6)",
    "signature": "Typography at architectural scale — headlines so large they become abstract forms, letters cropped by the viewport and stacked like infrastructure. The differential between 10vw hero type and 0.75rem nav labels creates cinematic tension, with the type grid treated as the layout itself."
  },
  {
    "id": "29",
    "name": "Aktiv",
    "url": "https://aktiv.studio",
    "award": "CSSDA Best Agency 2024",
    "category": "Agency / Swiss Grid",
    "mode": "light",
    "tagline": "Swiss restraint in a cream palette — Aktiv Grotesk as both brand and tool.",
    "principles": ["Grid as language — followed rigorously, broken intentionally", "40% of any section is intentionally empty", "Asymmetry is architectural, not accidental", "Mixed-weight headlines: thin + bold juxtaposition", "Flat color and grain texture over gradients"],
    "fonts": { "sans": "\"Aktiv Grotesk\", \"Inter\", \"Helvetica Neue\", system-ui, sans-serif", "display": "\"Aktiv Grotesk\", \"Inter\", \"Helvetica Neue\", system-ui, sans-serif", "mono": null },
    "typeScale": { "display": "128px", "h1": "80px", "h2": "48px", "body": "15px" },
    "weights": { "heading": 700, "body": 400 },
    "letterSpacingDisplay": "-0.01em",
    "colors": { "bg": "#FAFAF8", "bgAlt": "#F0EFEB", "surface": "#EAE8E1", "text": "#111110", "textMuted": "#8C8C8A", "border": "#DCDCD8", "primary": "#111110", "primaryHover": "#000000", "onPrimary": "#FAFAF8", "accent2": "#C8B89A" },
    "heroGradient": "linear-gradient(135deg, #FAFAF8 0%, #F0EFEB 100%)",
    "radius": "4px", "buttonRadius": "8px", "shadow": "0 2px 12px rgba(0, 0, 0, 0.06)",
    "signature": "The namesake typeface is the design system — Aktiv Grotesk at every scale from 8vw hero to 11px nav labels creates a coherent voice where size and weight are the only variables. Clean without being empty, structured without being rigid, with a warm cream palette and intentional grid breaks."
  },
  {
    "id": "30",
    "name": "Mother Design",
    "url": "https://motherdesign.com",
    "award": "D&AD Pencil, Awwwards SOTD",
    "category": "Studio / Confident Minimal",
    "mode": "light",
    "tagline": "Light Canela serif on warm cream — an art book that happens to be a website.",
    "principles": ["Image-forward — the work is the hero, text frames it", "Editorial restraint: thin serifs and silence over bold", "Minimal color, maximum presence", "Asymmetric grid serves the imagery", "Color delivered through photography, not gradient fills"],
    "fonts": { "sans": "\"Akkurat\", \"Neue Haas Grotesk\", \"Helvetica Neue\", system-ui, sans-serif", "display": "\"Canela\", Georgia, \"Times New Roman\", serif", "mono": null },
    "typeScale": { "display": "120px", "h1": "88px", "h2": "56px", "body": "17px" },
    "weights": { "heading": 400, "body": 300 },
    "letterSpacingDisplay": "-0.01em",
    "colors": { "bg": "#F9F7F4", "bgAlt": "#F2EFE9", "surface": "#E5DFD6", "text": "#2A2520", "textMuted": "#6B6358", "border": "#D9D3CB", "primary": "#2A2520", "primaryHover": "#161412", "onPrimary": "#F9F7F4", "accent2": "#C4704A" },
    "heroGradient": "linear-gradient(180deg, transparent 50%, rgba(22,20,18,0.7) 100%)",
    "radius": "0px", "buttonRadius": "100px", "shadow": "0 24px 64px rgba(0, 0, 0, 0.08)",
    "signature": "A masterclass in typographic restraint — Canela serif at light weight creates luxury without ostentation, using thin serifs and silence to communicate taste where others use bold. Warm cream backgrounds and barely-there hierarchy make the site feel like an art book."
  },
  {
    "id": "31",
    "name": "Porsche Taycan",
    "url": "https://www.porsche.com/taycan",
    "award": "iF Design Award, Webby",
    "category": "Automotive / Performance Luxury",
    "mode": "dark",
    "tagline": "Razor-sharp zero-radius precision — cinema staged for a single product.",
    "principles": ["Cinema for one product — sections like film chapters", "Imagery is everything: full-bleed photo and video", "Minimal UI, maximum drama", "Thin-weight type at dramatic scale", "Specs presented with the reverence of artistic statements"],
    "fonts": { "sans": "\"Porsche Next\", Arial, system-ui, sans-serif", "display": "\"Porsche Next\", Arial, system-ui, sans-serif", "mono": null },
    "typeScale": { "display": "96px", "h1": "80px", "h2": "48px", "body": "16px" },
    "weights": { "heading": 400, "body": 400 },
    "letterSpacingDisplay": "-0.01em",
    "colors": { "bg": "#000000", "bgAlt": "#0A0A0A", "surface": "#1C1C1C", "text": "#FFFFFF", "textMuted": "#B2B2B2", "border": "#464646", "primary": "#FFFFFF", "primaryHover": "rgba(255,255,255,0.9)", "onPrimary": "#000000", "accent2": "#3B78C4" },
    "heroGradient": "linear-gradient(180deg, rgba(0,0,0,0) 0%, rgba(0,0,0,0.85) 100%)",
    "radius": "0px", "buttonRadius": "0px", "shadow": "0 4px 24px rgba(0, 0, 0, 0.6)",
    "signature": "The sharp-corner, zero-radius design language — in a world of rounded corners, every button, card and container has razor-sharp 0px radius, communicating precision engineering with no softening. Combined with thin-weight typography at dramatic scale, it feels built for a car that corners at 0.1g."
  },
  {
    "id": "32",
    "name": "Rivian",
    "url": "https://rivian.com",
    "award": "Webby Winner Automotive",
    "category": "Automotive / Adventure Editorial",
    "mode": "light",
    "tagline": "Forest greens and earthy tones — the green is earned, not a sustainability cliche.",
    "principles": ["Nature meets precision — landscape photo as emotional anchor", "Green connects both worlds: forest AND brand", "Generous, breathable layouts mirroring open spaces", "Specs given the same weight as adventure stories", "Clean humanist type, functional with warmth"],
    "fonts": { "sans": "\"Rivian\", \"Inter\", system-ui, sans-serif", "display": "\"Rivian\", \"Inter\", system-ui, sans-serif", "mono": null },
    "typeScale": { "display": "88px", "h1": "64px", "h2": "48px", "body": "16px" },
    "weights": { "heading": 600, "body": 400 },
    "letterSpacingDisplay": "-0.01em",
    "colors": { "bg": "#F8FAF8", "bgAlt": "#EBF4EE", "surface": "#FFFFFF", "text": "#1C1C1C", "textMuted": "#6B7280", "border": "#E2E8F0", "primary": "#3D7A4A", "primaryHover": "#2C4A30", "onPrimary": "#FFFFFF", "accent2": "#3A5070" },
    "heroGradient": "linear-gradient(135deg, #F8FAF8 0%, #EBF4EE 100%)",
    "radius": "16px", "buttonRadius": "100px", "shadow": "0 4px 24px rgba(0, 0, 0, 0.06)",
    "signature": "The green is earned — Rivian's #3D7A4A is the actual color of the environments their vehicles explore, so every button, stat and border recalls forest trails and mountain passes. Rugged landscape photography in tension with precise UI produces a voice that is capable, purposeful, and alive."
  },
  {
    "id": "33",
    "name": "Allbirds",
    "url": "https://www.allbirds.com",
    "award": "Webby Winner Commerce",
    "category": "E-commerce / Sustainable Warm",
    "mode": "light",
    "tagline": "Earthy, honest commerce without pressure — a palette made of the materials themselves.",
    "principles": ["Comfortable, sustainable, honest", "Anti-corporate, approachable typography", "Calm browsing over urgency tactics", "Color palette ideologically consistent with the brand mission", "Clean product photography in natural settings"],
    "fonts": { "sans": "\"Allbirds Sans\", \"Helvetica Neue\", system-ui, sans-serif", "display": "\"Tiempos Headline\", Georgia, serif", "mono": null },
    "typeScale": { "display": "72px", "h1": "56px", "h2": "40px", "body": "15px" },
    "weights": { "heading": 700, "body": 400 },
    "letterSpacingDisplay": "0",
    "colors": { "bg": "#F5F0E8", "bgAlt": "#EDE7D9", "surface": "#FFFFFF", "text": "#3A2820", "textMuted": "#B59A80", "border": "#D9CEBC", "primary": "#3A2820", "primaryHover": "#282018", "onPrimary": "#FFFFFF", "accent2": "#2D4030" },
    "heroGradient": "linear-gradient(135deg, #F5F0E8 0%, #EDE7D9 100%)",
    "radius": "4px", "buttonRadius": "4px", "shadow": "0 4px 16px rgba(0, 0, 0, 0.06)",
    "signature": "Every shade in the system — oat, bark, clay, wool gray — is a direct reference to the natural materials Allbirds uses. The design makes the color palette feel ideologically consistent with the sustainability mission, not just decoratively matching. You feel the ethics in the UX."
  },
  {
    "id": "34",
    "name": "Glossier",
    "url": "https://www.glossier.com",
    "award": "Webby Honoree",
    "category": "Beauty / Millennial Pink",
    "mode": "light",
    "tagline": "Millennial pink softness with disciplined restraint — beauty that's already on your skin.",
    "principles": ["Soft, effortless, and for you", "The product IS the palette", "Disciplined restraint over feature clutter", "Community woven in to validate and inspire", "Invite, never pressure"],
    "fonts": { "sans": "\"Graphik\", \"Helvetica Neue\", system-ui, sans-serif", "display": "\"Graphik\", \"Helvetica Neue\", system-ui, sans-serif", "mono": null },
    "typeScale": { "display": "64px", "h1": "48px", "h2": "32px", "body": "15px" },
    "weights": { "heading": 400, "body": 300 },
    "letterSpacingDisplay": "0",
    "colors": { "bg": "#FDF8F6", "bgAlt": "#FAF0EC", "surface": "#FFFFFF", "text": "#4A3830", "textMuted": "#C4A89E", "border": "#F0C4BA", "primary": "#1A1414", "primaryHover": "#4A3830", "onPrimary": "#FFFFFF", "accent2": "#F5DAD2" },
    "heroGradient": "radial-gradient(ellipse at 60% 0%, #F5DAD2 0%, #FDF8F6 60%)",
    "radius": "8px", "buttonRadius": "4px", "shadow": "0 2px 12px rgba(0, 0, 0, 0.05)",
    "signature": "The color is a cultural artifact, not just a brand choice. 'Millennial pink' entered the design vernacular partly because of Glossier's disciplined deployment of #F5DAD2 and its relatives. Every pink element reinforces beauty that's soft, effortless, and never aggressive."
  },
  {
    "id": "35",
    "name": "Aesop",
    "url": "https://www.aesop.com",
    "award": "Multiple design awards",
    "category": "Luxury / Typographic Restraint",
    "mode": "light",
    "tagline": "Literary luxury — libraries, apothecaries and rare bookshops rendered as a website.",
    "principles": ["Copy at the center — design assumes you want to read", "The page as page — book-like margins and rhythm", "Generous whitespace, narrow type columns", "Product within a world of literature and philosophy", "Restraint and pigment-like, natural transitions"],
    "fonts": { "sans": "\"Futura PT\", \"Helvetica Neue\", system-ui, sans-serif", "display": "\"Vendetta\", \"Canela\", Georgia, \"Times New Roman\", serif", "mono": null },
    "typeScale": { "display": "80px", "h1": "64px", "h2": "44px", "body": "18px" },
    "weights": { "heading": 400, "body": 400 },
    "letterSpacingDisplay": "-0.01em",
    "colors": { "bg": "#F4EFE6", "bgAlt": "#EEE8DC", "surface": "#FFFFFF", "text": "#1A1410", "textMuted": "#B8AD98", "border": "#D8CEBC", "primary": "#1A1410", "primaryHover": "#3A2E20", "onPrimary": "#F4EFE6", "accent2": "#8B5E3C" },
    "heroGradient": "linear-gradient(135deg, #F4EFE6 0%, #EEE8DC 100%)",
    "radius": "0px", "buttonRadius": "0px", "shadow": "0 4px 20px rgba(58, 46, 32, 0.08)",
    "signature": "Aesop is one of the only luxury brands whose website design assumes the visitor can and wants to read. Body text is 18px at 1.8 line-height in a serif designed for book setting, with navigation, layout, and whitespace all arranged in service of words. A radically differentiated literary design ethic."
  },
  {
    "id": "36",
    "name": "Loom",
    "url": "https://www.loom.com",
    "award": "Webby Winner Productivity",
    "category": "SaaS / Friendly Purple",
    "mode": "light",
    "tagline": "Warm purple-violet product energy that says video is for everyone — bright, friendly, never cold.",
    "principles": ["Video is for everyone — accessible and encouraging", "Video-native — every screenshot is a recording", "Vibrant but never overwhelming", "Color journey from hero energy to clean comprehension", "Dark sections shift emotional register, not just aesthetics"],
    "fonts": { "sans": "\"Inter\", system-ui, -apple-system, sans-serif", "display": "\"Inter\", system-ui, -apple-system, sans-serif", "mono": null },
    "typeScale": { "display": "72px", "h1": "56px", "h2": "40px", "body": "16px" },
    "weights": { "heading": 700, "body": 400 },
    "letterSpacingDisplay": "-0.02em",
    "colors": { "bg": "#FAFAFA", "bgAlt": "#F0EFFF", "surface": "#FFFFFF", "text": "#0F0F1A", "textMuted": "#9898B0", "border": "#E4E4F0", "primary": "#625DF5", "primaryHover": "#4B46D9", "onPrimary": "#FFFFFF", "accent2": "#FF6B6B" },
    "heroGradient": "linear-gradient(135deg, #625DF5 0%, #8B87FF 100%)",
    "radius": "16px", "buttonRadius": "8px", "shadow": "0 4px 16px rgba(98, 93, 245, 0.35)",
    "signature": "The recording UI is always visible — a camera pip, a recording indicator, a screen capture frame, or a timeline scrubber. The product's core interaction (pressing record) is never far from view, keeping the value proposition constantly alive. You don't just read 'record a video' — you see someone already recording."
  },
  {
    "id": "37",
    "name": "Descript",
    "url": "https://www.descript.com",
    "award": "Multiple Webby Awards",
    "category": "Creative Tool / Playful",
    "mode": "light",
    "tagline": "Creative energy with professional grounding — powerful tools made friendly in warm coral.",
    "principles": ["Powerful tools made friendly", "Show the work — demonstrate, don't describe", "Playful but never childish", "Coral accent only on things that matter: CTAs and feature highlights", "Vibrant for creators, structured for teams"],
    "fonts": { "sans": "\"Inter\", system-ui, -apple-system, sans-serif", "display": "\"Inter\", system-ui, -apple-system, sans-serif", "mono": null },
    "typeScale": { "display": "72px", "h1": "56px", "h2": "40px", "body": "16px" },
    "weights": { "heading": 700, "body": 400 },
    "letterSpacingDisplay": "-0.02em",
    "colors": { "bg": "#FAFAF8", "bgAlt": "#F5F4F0", "surface": "#FFFFFF", "text": "#1A1A14", "textMuted": "#8A8880", "border": "#E0DDD6", "primary": "#FF5B35", "primaryHover": "#E84E2A", "onPrimary": "#FFFFFF", "accent2": "#FF8060" },
    "heroGradient": "linear-gradient(135deg, #FAFAF8 0%, #F5F4F0 100%)",
    "radius": "16px", "buttonRadius": "8px", "shadow": "0 4px 16px rgba(255, 91, 53, 0.3)",
    "signature": "The product interface is the hero. Rather than static screenshots, Descript shows the editing happening — words getting struck through, audio waveforms shifting, video frames updating in sync with text changes. The coral accent is warm enough to feel creative, structured enough to feel professional."
  },
  {
    "id": "38",
    "name": "Headspace",
    "url": "https://headspace.com",
    "award": "Webby + Apple Design Award",
    "category": "Wellness / Warm Illustration",
    "mode": "light",
    "tagline": "Every interaction feels like a gentle exhale — softness as a feature, not a weakness.",
    "principles": ["Wellness doesn't have to look clinical — softness is a feature", "Warmth through radius — soft, unthreatening environment", "Orange as emotional anchor, used only for action", "Illustration over photography for a unique world", "Breathing as design language — the 4-second rhythm permeates motion"],
    "fonts": { "sans": "\"GT Walsheim\", -apple-system, sans-serif", "display": "\"GT Walsheim\", -apple-system, sans-serif", "mono": null },
    "typeScale": { "display": "48px", "h1": "36px", "h2": "28px", "body": "16px" },
    "weights": { "heading": 700, "body": 400 },
    "letterSpacingDisplay": "-0.03em",
    "colors": { "bg": "#FFFAF0", "bgAlt": "#F0EDE8", "surface": "#FFFFFF", "text": "#2B2D42", "textMuted": "#A0A3BD", "border": "#F0EDE8", "primary": "#F47D31", "primaryHover": "#E8692180", "onPrimary": "#FFFFFF", "accent2": "#06D6A0" },
    "heroGradient": "linear-gradient(135deg, #FFB88C 0%, #FFD166 100%)",
    "radius": "20px", "buttonRadius": "28px", "shadow": "0 8px 24px rgba(43, 45, 66, 0.1)",
    "signature": "Heavy 20–28px border-radius on everything creates a soft, unthreatening environment, paired with a single warm orange used only for action. Custom organic illustrations build a world competitors can't copy, and a 4-second breathing animation rhythm — even loading states are breathing circles, never spinners — permeates all motion."
  },
  {
    "id": "39",
    "name": "Read.cv",
    "url": "https://read.cv",
    "award": "Awwwards SOTD, FWA",
    "category": "Portfolio / Typographic Restraint",
    "mode": "light",
    "tagline": "The anti-LinkedIn — the typographic equivalent of a well-tailored suit, no embellishment.",
    "principles": ["Restraint is the brand — doing less communicates taste", "640px is the magic number for an optimal reading measure", "Grayscale as palette — carefully chosen grays need no color", "No animation as a deliberate choice", "Typography carries everything when there's no decoration"],
    "fonts": { "sans": "\"Inter\", -apple-system, BlinkMacSystemFont, system-ui, sans-serif", "display": "\"Inter\", -apple-system, BlinkMacSystemFont, system-ui, sans-serif", "mono": "\"JetBrains Mono\", \"SF Mono\", Menlo, monospace" },
    "typeScale": { "display": "36px", "h1": "28px", "h2": "20px", "body": "15px" },
    "weights": { "heading": 600, "body": 400 },
    "letterSpacingDisplay": "-0.02em",
    "colors": { "bg": "#FFFFFF", "bgAlt": "#FAFAFA", "surface": "#FFFFFF", "text": "#171717", "textMuted": "#737373", "border": "#E5E5E5", "primary": "#0066FF", "primaryHover": "#0052CC", "onPrimary": "#FFFFFF", "accent2": "#00A870" },
    "heroGradient": "linear-gradient(180deg, #FFFFFF 0%, #FAFAFA 100%)",
    "radius": "8px", "buttonRadius": "8px", "shadow": "none",
    "signature": "Black and white do 95% of the work — an 11-step grayscale is the palette, with blue reserved exclusively for links. No gradients, no scroll animations, no parallax; the absence of animation IS the design statement. Everything centers on a 640px reading column that makes each element feel considered."
  },
  {
    "id": "40",
    "name": "Teenage Engineering",
    "url": "https://teenage.engineering",
    "award": "D&AD Yellow Pencil + iF Design",
    "category": "Product / Industrial Brutalism",
    "mode": "light",
    "tagline": "The internet as a product manual from the future — utility is beauty, the website stays invisible.",
    "principles": ["Utility IS beauty — the most beautiful thing is the thing that works", "Zero radius, zero compromise — rectangular everything", "Monochrome as ideology — black/white forces products to provide color", "Spec sheets are beautiful when the typography is perfect", "Small type, big confidence — product photography does the selling"],
    "fonts": { "sans": "\"TE Neue\", \"Helvetica Neue\", Helvetica, Arial, sans-serif", "display": "\"TE Neue\", \"Helvetica Neue\", Helvetica, Arial, sans-serif", "mono": "\"TE Mono\", \"SF Mono\", Menlo, Consolas, monospace" },
    "typeScale": { "display": "72px", "h1": "32px", "h2": "18px", "body": "14px" },
    "weights": { "heading": 700, "body": 400 },
    "letterSpacingDisplay": "-0.04em",
    "colors": { "bg": "#FFFFFF", "bgAlt": "#F5F5F5", "surface": "#F5F5F5", "text": "#000000", "textMuted": "#666666", "border": "#E0E0E0", "primary": "#000000", "primaryHover": "rgba(0,0,0,0.85)", "onPrimary": "#FFFFFF", "accent2": "#FF6600" },
    "heroGradient": "#FFFFFF",
    "radius": "0px", "buttonRadius": "0px", "shadow": "none",
    "signature": "The entire site is pure #000 black text on pure #FFF white, with product accent colors appearing only on product images and buy buttons. Zero border-radius makes everything rectangular, creating an industrial tool-like identity. The design stays invisible so high-res studio product photography can be the entire experience."
  }
];
